name: CI
on: 
  push:
  pull_request:
  workflow_call:
jobs:
  verifications:
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.4.0
        with:
          java-version: '17.0.3+7'
      - run: mvn package
  unit-tests:
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.4.0
        with:
          java-version: '17.0.3+7'
      - run: mvn test